before_script:
  -	export PATH=/opt/Catapult-10.3a/Mgc_home/bin:$PATH
	- export LM_LICENSE_FILE=1717@licence.irisa.fr:2100@licence.irisa.fr
  - mkdir -p cache

cache:
  paths:
    - cache

stages:
  - build
  - test

# Note: we cannot use submodule commit as cache key, so we do it manually in
# subfolder of a big cache
cbuild:
  stage: build
  script:
		- mkdir build
		- cd build
		- cmake ..
		- make all

hls:
  stage: build
  artifacts:
    paths:
      - Catapult/doCore.v1/
    expire_in: 1 day
  script:
    - mkdir build-catapult
    - cd build-catapult
    - catapult -shell -file $CI_PROJECT_DIR/scripts/catapult.tcl

test:atomic:
  stage: test
  script:
    - cd build/bin
    - ./atomicTest $CI_PROJECT_DIR/benchmarks/autoTests/atomic.txt

